// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
  skills: dynamic(() => import("./Skills")),
};
