// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  contact: dynamic(() => import("./Contact")),
  freelance_about: dynamic(() => import("./FreelanceAbout")),
  freelance_help: dynamic(() => import("./FreelanceHelp")),
  freelance_hero: dynamic(() => import("./FreelanceHero")),
  freelance_services: dynamic(() => import("./FreelanceServices")),
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
  skills: dynamic(() => import("./Skills")),
};
